### ISSUE TITLE
Method not found: 'SpeciesList Landis.Library.SiteHarvest.BasicParameterParser`1.ReadSpeciesToPlant()'.

### ISSUE THREAD

**Issue by geryan** [LANDIS-II-Foundation/Extension-Biomass-Harvest#50]
I'm not certain if this is actually an issue with this extension or the Harvest management library.

Landis v7 recently installed from github on Ubuntu 18.04.1 and running dotnet 2.2.8.  Works fine when Biomass Harvest extension is turned off, but fails when loading Biomass Harvest Extension.

```
Loading Biomass Harvest extension ...
   Registering Data:  Harvest.PrescriptionName.
   Registering Data:  Harvest.TimeOfLastEvent.
   Registering Data:  Harvest.CohortsDamaged.
Internal error occurred within the program:
  Method not found: 'SpeciesList Landis.Library.SiteHarvest.BasicParameterParser`1.ReadSpeciesToPlant()'.

Stack trace:
   at Landis.Library.HarvestManagement.InputParametersParser.ReadPrescriptions(List`1 prescriptions, Int32 harvestTimestep)
   at Landis.Library.HarvestManagement.InputParametersParser.Parse()
   at Landis.Utilities.TextParser`1.Parse(LineReader reader)
   at Landis.Data.Load[T](String path, ITextParser`1 parser)
   at Landis.Extension.BiomassHarvest.PlugIn.LoadParameters(String dataFile, ICore mCore)
   at Landis.Model.LoadExtensions(ExtensionAndInitFile[] extensions)
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args) in /opt/Core-Model-v7-LINUX/Tool-Console/src/App.cs:line 99
```

We've run these scripts in the past with no problems and the appropriate libraries appear to be installed but new installation is failing. Lost from here.

Thanks,

Gerry

**Comment by rmscheller** [comment]
Gerry, 

Are you running the latest Biomass Harvest installer?  I thought this issue was fixed.  If not, contact Eric Gustafson directly as he is the chief harvest developer.  I've also flagged Austin here, who has worked on harvest most recently.

Rob

**Comment by geryan** [comment]
Thanks Rob

Should be the latest installer as it was cloned directly from the github repository master branch so will be what is up here.

I'll contact Eric directly. I can find a USDA email address, but please ping me if that's unlikely to be the best one.

Cheers,

Gerry

**Comment by rmscheller** [comment]
Gerry,
And you also updated the harvest libraries?  That is where the bulk of the code resides.

**Comment by geryan** [comment]
Hi Rob, yes - all freshly installed from the github repos.

**Comment by rdt12** [comment]
Hi Gerry,

Did you ever solve your problem? I'm seeing the same error under Ubuntu 16.04 and dotnet 2.0.0?

I'm installing:

https://github.com/LANDIS-II-Foundation/Extension-Base-Harvest/archive/v4.1.zip
https://github.com/LANDIS-II-Foundation/Extension-Biomass-Harvest/archive/v4.1.zip

**Comment by rdt12** [comment]
Hi,

I solved my problem. I was building using a script that references a number of "archive/*.zip" files, but checked out the repository:

        https://github.com/LANDIS-II-Foundation/Support-Library-Dlls-v7.git

There must have been an incompatible change introduced at some time in that repo. I checked out commit:

     63978adf8ea85e9f7e89beee8bfb2df1bc835371

(just before the last time the container was successfully built) from the Support-Library_Dlls-v7 repo and built a version that runs without error.

So, my error was not a problem with Extension-Biomass-Harvest.

**Comment by rmscheller** [comment]
Ron,

I'm not sure I follow.  Where do these archive/zip files reside?  And the current commit is working, or an older commit?  

Thanks!

Rob

**Comment by VincentBG98** [comment]
Hello,

I post my issue here as it is quite similar of the first one. I unfortunately not understand the solution find by Mr. Tapia.

You'll find below the issue given by the log and attached the settings of the extension (I'm using Landis-II 7.0 and Biomass Harvest 4.3).

> 2021-04-05 16:52:10,894 - Running Biomass Harvest ...
2021-04-05 16:52:12,204 - Internal error occurred within the program:
2021-04-05 16:52:12,206 -   Object reference not set to an instance of an object.
2021-04-05 16:52:12,207 - 
2021-04-05 16:52:12,207 - Stack trace:
2021-04-05 16:52:12,227 -    at Landis.Library.HarvestManagement.FireRiskRank.ComputeRank(Stand stand, Int32 i)
   at Landis.Library.HarvestManagement.StandRankingMethod.Landis.Library.HarvestManagement.IStandRankingMethod.RankStands(List`1 stands, StandRanking[] rankings)
   at Landis.Library.HarvestManagement.AppliedPrescription.InitializeForHarvest(List`1 stands)
   at Landis.Library.HarvestManagement.ManagementArea.HarvestStands()
   at Landis.Extension.BiomassHarvest.PlugIn.Run()
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args) in C:\Users\Austen\Documents\GitHub\Core-Model-v7\Tool-Console\src\App.cs:line 98

[biom-harvest-Business-as-usual.txt](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Harvest/files/6414627/biom-harvest-Business-as-usual.txt)

Thanks,

Vincent

**Comment by rmscheller** [comment]
Vincent,

Fire Risk Rank might depend on using the Dynamic Fuels extension; it may not be compatible with SCRPPLE.

R

**Comment by VincentBG98** [comment]
Rob, 

It is more simple than it seems...

Thanks a lot !
